---
# Execute with:
#   ansible-builder build -v 3 -t my-ee:latest -f execution-environment.yml
# Targeting:
#   ansible (meta package) == 8
#   ansible-core == 2.15
# Customized from:
#   https://github.com/ansible-community/images/blob/30a430c2cf2db83806c226eb1ac0c38307877a55/execution-environments/2.15-with-ansible8/execution-environment.yml

version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
dependencies:
  ansible_core:
    package_pip: 'ansible-core<2.16'
  ansible_runner:
    package_pip: ansible-runner
  system:
    - openssh-clients
    - sshpass
    - git
  # TODO:  Galaxy collections MAY not be necessary due to `pip install ansible`
  # below, and removing version to allow for latest is desired.  Investigate if
  # required during build.
  galaxy:
    collections:
      - name: ansible.posix
        version: 1.5.0
      - name: ansible.utils
        version: 2.10.0
      - name: ansible.windows
        version: 1.14.0

# additional_build_files:
#   - src: ../shared/*.pem
#     dest: files

additional_build_steps:
  prepend_base:
    # - ADD _build/files/*.pem /etc/pki/ca-trust/source/anchors/
    # - RUN update-ca-trust
    - RUN dnf install -y python3 python3-setuptools python3-pip python3-devel
    - RUN dnf clean all
  append_final:
    - RUN pip3 install 'ansible<9'
